In [39]:
#实际上，实例变量就是一个用 self 修饰的变量。self 将一个变量绑定到一个特定的实例上，这样它就属于这实例自己。实例变量可以创建类实例引用，output=30变量就是不对外可见
class A(object):
    va = 10

    def __init__(self):
       
        self.input = 20
        output=30
        self.all=output

In [40]:
obj1=A.va

In [34]:
obj1

10

In [35]:
obj2=A()

In [36]:
obj2.va

10

In [37]:
obj2.input

20

In [30]:
obj2.output

AttributeError: 'A' object has no attribute 'output'

In [38]:
obj2.all

30

In [1]:
import tensorflow as tf 
import numpy as np

In [28]:
A=[[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
B=[[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
C=[]
C.append(A)
C.append(B)
h_pool = tf.concat(C, 1)
sess = tf.Session()


In [29]:
b=tf.shape(h_pool)
print(sess.run(b))

[2 4 3]


# 

In [29]:
import numpy as np
a=[]
a.append(np.array([3,2]))
a.append(np.array([1,2]))
a=np.array(a)


In [30]:
shuffle_indices=np.random.permutation(len(a))
shuffle_indices

array([0, 1])

In [31]:
b=a[shuffle_indices]

In [32]:
b

array([[3, 2],
       [1, 2]])